### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by mcekwonu** [prmiles/pymcmcstat#100]
**Describe the bug**
pymcmcstat version >= 1.9.0, 1.9.1 failed to import pi from scipy when ```import pymcmcstat is called```.

**To Reproduce**
1. Go to 'python IDE'
2. import pymcmcstat
3. See error: Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/drmce/.drmce_venv/lib/python3.11/site-packages/pymcmcstat/__init__.py", line 3, in <module>
    from mcmcplot import mcmcplot  # noqa, flake8 issue
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/drmce/.drmce_venv/lib/python3.11/site-packages/mcmcplot/mcmcplot.py", line 9, in <module>
    from . import mcmatplot as _mcmpl
  File "/home/drmce/.drmce_venv/lib/python3.11/site-packages/mcmcplot/mcmatplot.py", line 13, in <module>
    from .utilities import generate_names, make_x_grid
  File "/home/drmce/.drmce_venv/lib/python3.11/site-packages/mcmcplot/utilities.py", line 9, in <module>
    from scipy import pi, sin, cos
ImportError: cannot import name 'pi' from 'scipy' (/home/drmce/.drmce_venv/lib/python3.11/site-packages/scipy/__init__.py)

**Expected behavior**
import pymcmcstat.

**Desktop (please complete the following information):**
 - OS: Ubuntu 24.04
 - Version 24.04

**Comment by gtomass** [comment]
Pymcmcstat do not work with the latest version of scipy 1.14.1, try replacing `from scipy import pi, sin, cos` by
`from math import pi, sin, cos`
