### ISSUE TITLE
Propagation module not working with matplotlib 3.3.3

### ISSUE THREAD

**Issue by prmiles** [prmiles/pymcmcstat#87]
**Describe the bug**
Some feature is no longer available in matplotlib 3.3.3 (_facecolor3d???)

```
AttributeError: 'Poly3DCollection' object has no attribute '_facecolors3d'
```

**To Reproduce**
Run the test suite with matplotlib 3.3.3 installed.

**Expected behavior**
It should not so picky about matplotlib.

**Comment by prmiles** [comment]
https://stackoverflow.com/questions/54994600/pyplot-legend-poly3dcollection-object-has-no-attribute-edgecolors2d

**Comment by prmiles** [comment]
This will be released as part of v1.9.2
